version: '3.8'

services:
  broker-service:
    build: .
    ports:
      - "8080:8080"
    networks:
      - broker-network
    environment:
      - PROMETHEUS_METRICS=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - broker-network

networks:
  broker-network:
    driver: bridge
